root = "."
tmp_dir = "tmp"

[build]
  # Сначала запускаем генерацию шаблонов
  pre_cmd = ["templ generate"]
  # Затем собираем бинарный файл
  cmd = "go build -o ./tmp/main.exe ./cmd/app/main.go"
  # Путь для запуска (с двойным слэшем для Windows)
  bin = "tmp\\main.exe"
  
  delay = 500
  include_ext = ["go", "templ", "html", "css"]
  exclude_dir = ["tmp", "vendor", "static"]
  # Игнорируем сгенерированные файлы, чтобы избежать бесконечного цикла
  exclude_regex = ["_templ.go"]
  stop_on_error = true

[color]
  main = "magenta"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true